server:
  port: 81
spring:
  application:
    name: cloud-consumer-order
  zip-kin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率介于0到1之间，1表示全部采集
      probability: 1
eureka:
  instance:
    hostname: www.eureka7001.com
  client:
    fetch-registry: true #不注册服务
    register-with-eureka: true #不检索服务
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/
      #defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/